// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAPIV2MessagesParams creates a new GetAPIV2MessagesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIV2MessagesParams() *GetAPIV2MessagesParams {
	return &GetAPIV2MessagesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV2MessagesParamsWithTimeout creates a new GetAPIV2MessagesParams object
// with the ability to set a timeout on a request.
func NewGetAPIV2MessagesParamsWithTimeout(timeout time.Duration) *GetAPIV2MessagesParams {
	return &GetAPIV2MessagesParams{
		timeout: timeout,
	}
}

// NewGetAPIV2MessagesParamsWithContext creates a new GetAPIV2MessagesParams object
// with the ability to set a context for a request.
func NewGetAPIV2MessagesParamsWithContext(ctx context.Context) *GetAPIV2MessagesParams {
	return &GetAPIV2MessagesParams{
		Context: ctx,
	}
}

// NewGetAPIV2MessagesParamsWithHTTPClient creates a new GetAPIV2MessagesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIV2MessagesParamsWithHTTPClient(client *http.Client) *GetAPIV2MessagesParams {
	return &GetAPIV2MessagesParams{
		HTTPClient: client,
	}
}

/* GetAPIV2MessagesParams contains all the parameters to send to the API endpoint
   for the get API v2 messages operation.

   Typically these are written to a http.Request.
*/
type GetAPIV2MessagesParams struct {

	/* Limit.

	   Number of messages

	   Format: int64
	   Default: 50
	*/
	Limit *int64

	/* Start.

	   Start index

	   Format: int64
	*/
	Start *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API v2 messages params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV2MessagesParams) WithDefaults() *GetAPIV2MessagesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API v2 messages params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV2MessagesParams) SetDefaults() {
	var (
		limitDefault = int64(50)

		startDefault = int64(0)
	)

	val := GetAPIV2MessagesParams{
		Limit: &limitDefault,
		Start: &startDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get API v2 messages params
func (o *GetAPIV2MessagesParams) WithTimeout(timeout time.Duration) *GetAPIV2MessagesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v2 messages params
func (o *GetAPIV2MessagesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v2 messages params
func (o *GetAPIV2MessagesParams) WithContext(ctx context.Context) *GetAPIV2MessagesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v2 messages params
func (o *GetAPIV2MessagesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v2 messages params
func (o *GetAPIV2MessagesParams) WithHTTPClient(client *http.Client) *GetAPIV2MessagesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v2 messages params
func (o *GetAPIV2MessagesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the get API v2 messages params
func (o *GetAPIV2MessagesParams) WithLimit(limit *int64) *GetAPIV2MessagesParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get API v2 messages params
func (o *GetAPIV2MessagesParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithStart adds the start to the get API v2 messages params
func (o *GetAPIV2MessagesParams) WithStart(start *int64) *GetAPIV2MessagesParams {
	o.SetStart(start)
	return o
}

// SetStart adds the start to the get API v2 messages params
func (o *GetAPIV2MessagesParams) SetStart(start *int64) {
	o.Start = start
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV2MessagesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Start != nil {

		// query param start
		var qrStart int64

		if o.Start != nil {
			qrStart = *o.Start
		}
		qStart := swag.FormatInt64(qrStart)
		if qStart != "" {

			if err := r.SetQueryParam("start", qStart); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
